/* eslint-disable no-console */
const fs = require('fs');
const path = require('path');

function parseEnv(content) {
  const out = {};
  const lines = content.split(/\r?\n/);
  for (const raw of lines) {
    const line = raw.trim();
    if (!line || line.startsWith('#')) continue;
    const idx = line.indexOf('=');
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    let value = line.slice(idx + 1).trim();
    // Strip quotes
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    out[key] = value;
  }
  return out;
}

function readEnvFile(envPath) {
  if (!fs.existsSync(envPath)) return null;
  return fs.readFileSync(envPath, 'utf8');
}

function main() {
  const root = path.join(__dirname, '..');
  const envPath = path.join(root, '.env');
  const fallbackPath = path.join(root, 'env.example');

  const content = readEnvFile(envPath) ?? readEnvFile(fallbackPath) ?? '';
  const env = parseEnv(content);

  const apiBaseUrl = env.API_BASE_URL || 'http://localhost:3000/api';

  const js = `// This file is auto-generated by scripts/generate-env.js
window.__env = window.__env || {};
window.__env.API_BASE_URL = ${JSON.stringify(apiBaseUrl)};
`;

  const outPath = path.join(root, 'src', 'assets', 'env.js');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, js, 'utf8');
  console.log(`[env] wrote ${outPath} (API_BASE_URL=${apiBaseUrl})`);
}

main();

